#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Check for log file to mount
while [ ! -f "/app/src/${SSH_AUTH_LOG_FILE_NAME}" ]; do sleep 1; echo "Waiting for ${SSH_AUTH_LOG_FILE_NAME} file.."; done
echo "______ENTRYPOINT_____"
exec "$@"
