version: "3"

services:
  watcher: &watcher
    build:
      context: .
      dockerfile: ./Dockerfile
    image: chowkidar-agent-watcher
    container_name: chowkidar-agent-watcher
    depends_on:
      - redis
    volumes:
      - ./:/app:z
      - ${SSH_AUTH_LOG_FILE_DIR}-${SSH_AUTH_LOG_FILE_NAME}:/app/${SSH_AUTH_LOG_FILE_NAME}
    env_file:
      - ./.env.sample
    command: /start-watcher

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *watcher
    image: chowkidar-agent-worker
    container_name: chowkidar-agent-worker
    depends_on:
      - redis
    ports: []
    command: celery -A src.celery_app worker -l INFO
