version: "3"

services:
  watcher: &watcher
    build:
      context: .
      dockerfile: ./Dockerfile
    image: chowkidar-agent-watcher
    container_name: chowkidar-agent-watcher
    depends_on:
      - redis
    volumes:
      - ${SSH_AUTH_LOG_FILE_DIR}${SSH_AUTH_LOG_FILE_NAME}:/app/src/${SSH_AUTH_LOG_FILE_NAME}
    env_file:
      - ./src/.env.sample
    command: /start-watcher

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *watcher
    image: chowkidar-agent-worker
    container_name: chowkidar-agent-worker
    depends_on:
      - redis
    command: /start-celery
